from datetime import UTC, datetime

from app.integrations.hubspot.associations import AssociationsRepository
from app.integrations.hubspot.client import HubSpotClient
from app.integrations.hubspot.models import HubSpotObject
from app.models.ai import LeadAnalysis


class ActivitiesRepository:
    def __init__(self, client: HubSpotClient, associations: AssociationsRepository) -> None:
        self.client = client
        self.associations = associations

    async def create_ai_note(
        self,
        *,
        contact_id: str,
        deal_id: str,
        analysis: LeadAnalysis,
        follow_up_draft: str,
    ) -> HubSpotObject:
        body = "\n".join(
            [
                "AI Lead Summary:",
                analysis.lead_summary,
                "",
                "Lead Urgency:",
                analysis.urgency,
                "",
                "Recommended Next Action:",
                analysis.recommended_next_action,
                "",
                "Follow-Up Draft (human review required; not sent):",
                follow_up_draft,
                "",
                "Generated By:",
                "AI Sales CRM Assistant",
            ]
        )
        data = await self.client.request(
            "POST",
            f"{self.client.objects_path}/notes",
            json={
                "properties": {
                    "hs_timestamp": datetime.now(UTC).isoformat(),
                    "hs_note_body": body,
                }
            },
        )
        note = HubSpotObject.model_validate(data)
        await self.associations.associate("notes", note.id, "contacts", contact_id)
        await self.associations.associate("notes", note.id, "deals", deal_id)
        return note
